### ISSUE TITLE
Feature Request - Pull and Push Alerts

### ISSUE THREAD

**Issue by mikeyw** [SagaHealthcareIT/mirthsync#17]
Hi Saga team. Thanks for a great tool!

Would it be possible to add Alerts to the push and pull operations?

**Comment by jessesaga** [comment]
Hi @mikeyw,

Thanks for the positive feedback. Yes, support could be added for Alerts and I think that's a great suggestion. Just to be clear - you're not talking about generating alerts but just allowing for pulling and pushing the alert configuration right?

**Comment by mikeyw** [comment]
Hi @jessesaga ,

Correct. My team currently exports the Alert configs for versioning in git.

Thanks!

**Comment by jessesaga** [comment]
The latest pre-release of mirthSync now supports pushing and pulling Alerts. https://github.com/SagaHealthcareIT/mirthsync/releases/tag/2.1.1
