### ISSUE TITLE
No [Default Group] subdirectory

### ISSUE THREAD

**Issue by skapteryx** [SagaHealthcareIT/mirthsync#18]
Just a usability suggestion.  Mirthsync places channel xml files in subfolders based upon their assigned subgroup - which makes sense.  However, channels that aren't explicitly assigned to a group seem to be placed by Mirth into a group called [Default Group], yet mirthsync places them in the root of the "Channels" directory in the target.  For consistency, consider either replicating the entire group structure (including a directory for Default Group) or dispense with groups entirely and place all files in a single (root) directory similar to the channel view (my personal preference).  Perhaps a flag to choose whether you want a group-based directory tree created, or not?
![Mirthsync_default_group](https://user-images.githubusercontent.com/81769143/113339207-025ddc00-92df-11eb-97e2-7c98b293cf79.png)

**Comment by jessesaga** [comment]
Feature implemented as of commit c8c2107
