### ISSUE TITLE
Add alternate password setting approach via env variables

### ISSUE THREAD

**Issue by jessesaga** [SagaHealthcareIT/mirthsync#32]
Currently mirthSync requires a "-p" command line switch for the password. Support should be added for pulling the password to use from an environment variable like MIRTHSYNC_PASSWORD.

ex. MIRTHSYNC_PASSWORD=somepassword java -jar mirthsync-standalone.jar -u admin -s https://localhost/api -t tmp

**Comment by elavy-harris** [comment]
Another useful variant would be to have an option to ask the user for the password.

**Comment by jessesaga** [comment]
implemented by #43
