### ISSUE TITLE
500 error when pushing to mirth instance

### ISSUE THREAD

**Issue by RyianRockers** [SagaHealthcareIT/mirthsync#33]
Using mirthsync 3.0.0 on AWS codebuild to deploy from a repo that uses the pull feature of mirthsync, I get a 500 error. See below;

<html>
<body>

DEBUG: posting xml to: /channelgroups/_bulkUpdate
--
291 | clojure.lang.ExceptionInfo: clj-http: status 500 {:cached nil, :request-time 55, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x68631b1d "org.apache.http.impl.client.InternalHttpClient@68631b1d"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Internal Server Error", :headers {"Access-Control-Allow-Headers" "Content-Type", "Server" "Jetty(9.4.21.v20190926)", "Content-Type" "application/xml", "Access-Control-Allow-Origin" "*", "Content-Length" "7621", "X-Frame-Options" "DENY", "Strict-Transport-Security" "max-age=31536000; includeSubDomains", "Connection" "close", "Access-Control-Allow-Methods" "GET, POST, DELETE, PUT", "Date" "Thu, 27 Jan 2022 15:44:00 GMT", "Access-Control-Allow-Credentials" "false", "Content-Security-Policy" "frame-ancestors 'none'"}, :orig-content-encoding nil, :status 500, :length 7621, :body "<com.mirth.connect.client.core.ControllerException>\n  <detailMessage>Channel &quot;84bbbe53-b03e-46bb-82af-1291ae479b7b&quot; belongs to more than one group.</detailMessage>\n  <stackTrace>\n    <trace>com.mirth.connect.server.controllers.DefaultChannelController.updateChannelGroups(DefaultChannelController.java:823)</trace>\n    <trace>com.mirth.connect.server.api.servlets.ChannelGroupServlet.updateChannelGroups(ChannelGroupServlet.java:54)</trace>\n    <trace>sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source)</trace>\n    <trace>sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)</trace>\n    <trace>java.lang.reflect.Method.invoke(Unknown Source)</trace>\n    <trace>com.mirth.connect.server.api.providers.MirthResourceInvocationHandlerProvider$1.invoke(MirthResourceInvocationHandlerProvider.java:219)</trace>\n    <trace>org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)</trace>\n    <trace>org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)</trace>\n    <trace>org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)</trace>\n    <trace>org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)</trace>\n    <trace>org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)</trace>\n    <trace>org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)</trace>\n    <trace>org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)</trace>\n    <trace>org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)</trace>\n    <trace>org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)</trace>\n    <trace>org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)</trace>\n    <trace>org.glassfish.jersey.internal.Errors.process(Errors.java:315)</trace>\n    <trace>org.glassfish.jersey.internal.Errors.process(Errors.java:297)</trace>\n    <trace>org.glassfish.jersey.internal.Errors.process(Errors.java:267)</trace>\n    <trace>org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)</trace>\n    <trace>org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)</trace>\n    <trace>org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)</trace>\n    <trace>org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)</trace>\n    <trace>org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)</trace>\n    <trace>org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)</trace>\n    <trace>org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)</trace>\n    <trace>org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)</trace>\n    <trace>com.mirth.connect.server.api.providers.StrictTransportSecurityFilter.doFilter(StrictTransportSecurityFilter.java:33)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)</trace>\n    <trace>com.mirth.connect.server.MethodFilter.doFilter(MethodFilter.java:37)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)</trace>\n    <trace>com.mirth.connect.server.api.providers.ClickjackingFilter.doFilter(ClickjackingFilter.java:44)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)</trace>\n    <trace>com.mirth.connect.server.api.providers.ApiOriginFilter.doFilter(ApiOriginFilter.java:71)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)</trace>\n    <trace>org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)</trace>\n    <trace>org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1589)</trace>\n    <trace>org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)</trace>\n    <trace>org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)</trace>\n    <trace>org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)</trace>\n    <trace>org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)</trace>\n    <trace>org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1559)</trace>\n    <trace>org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)</trace>\n    <trace>org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)</trace>\n    <trace>org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)</trace>\n    <trace>org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)</trace>\n    <trace>org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)</trace>\n    <trace>org.eclipse.jetty.server.Server.handle(Server.java:500)</trace>\n    <trace>org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)</trace>\n    <trace>org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:560)</trace>\n    <trace>org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)</trace>\n    <trace>org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)</trace>\n    <trace>org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)</trace>\n    <trace>org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)</trace>\n    <trace>org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:426)</trace>\n    <trace>org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:320)</trace>\n    <trace>org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)</trace>\n    <trace>org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)</trace>\n    <trace>org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)</trace>\n    <trace>org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)</trace>\n    <trace>org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)</trace>\n    <trace>org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)</trace>\n    <trace>org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)</trace>\n    <trace>org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)</trace>\n    <trace>org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)</trace>\n    <trace>org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)</trace>\n    <trace>java.lang.Thread.run(Unknown Source)</trace>\n  </stackTrace>\n  <suppressedExceptions class=\"java.util.Collections$UnmodifiableRandomAccessList\" resolves-to=\"java.util.Collections$UnmodifiableList\">\n    <c class=\"list\"/>\n    <list/>\n  </suppressedExceptions>\n</com.mirth.connect.client.core.ControllerException>", :trace-redirects []}

</body>
</html>

**Comment by jessesaga** [comment]
I think that this is the key - <com.mirth.connect.client.core.ControllerException>\n Channel "84bbbe53-b03e-46bb-82af-1291ae479b7b" belongs to more than one group.\n \n

Grep your target directory for the channel GUID. It sounds like there's an old duplicate one. Keep in mind that MirthSync doesn't currently handle renames or deletes gracefully. This means that when those things happen in a remote mirth and you pull .... you will end up with local duplicates that need to be cleaned up manually. One approach to working around this is to delete your target directory before pulling everything.

**Comment by RyianRockers** [comment]
Thanks for the information. I want to clarify though that every time we pull, we pull on top of a git clone to overwrite files that have been modified for source control.

**Comment by jessesaga** [comment]
Pulling over top of a clean git clone of a mirthSync target directory isn't enough to handle renames. You'd need to delete all previously pulled files from the target directory - then you do a mirthSync pull. That series of steps is a manual workaround to the fact that mirthSync does not currently handle deletes or renames gracefully. I already have a ticket created for this - #26

**Comment by jessesaga** [comment]
Closing this issue for now. Feel free to reopen if you think there's still an issue that needs to be addressed.
