### ISSUE TITLE
push -f for Code Template Libraries and Channel Groups

### ISSUE THREAD

**Issue by elavy-harris** [SagaHealthcareIT/mirthsync#38]
I'm using mirthSync 3.0.0.

If I have a Code Template Library and/or a Channel Group that has (a) has different revision numbers in Mirth and in the XML and (b) any modifications, I get the following, even with "push -f":

←[31mWARN ←[0;39m: An unexpected response was received from the server...
←[31mWARN ←[0;39m: Status: 200, Phrase: OK

This seems to be the same as #8, which supposedly was resolved in #9.

**Comment by jessesaga** [comment]
I can't replicate this locally. Do you see this same behavior in mirthSync 3.0.1? What version of Mirth are you pushing changes to?

**Comment by elavy-harris** [comment]
@jessesaga , were you able to reproduce this?

**Comment by jessesaga** [comment]
Sorry, I accidentally closed this issue. I'll try to reproduce this with Mirth 4.0.1 now that I have it incorporated into the test suite.

**Comment by jessesaga** [comment]
I've been able to reproduce this issue and I have a fix that I'll release soon. The bug was introduced in 3.0.0. Previous versions should behave properly.
